[[kaleido]]
arch = "aarch64"
git-tree-sha1 = "951484fc7c17437fd9c0dff6b9a4eba01a5ac10a"
libc = "glibc"
os = "linux"

    [[kaleido.download]]
    sha256 = "78846d6c07167adf18b5a5b7b2a5c7669e4bc4f35f44d54ac8854dc483f3d0a3"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/v0.5.0/kaleido_linux_arm64.tar.gz"
[[kaleido]]
arch = "x86_64"
git-tree-sha1 = "513ca13deb2b963957c730e2ea4c53be58bf41f6"
os = "macos"

    [[kaleido.download]]
    sha256 = "5184f439563dde633eec97aa13c59fd959e2eda23d788ede77bef4ff88ee5db1"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/v0.5.0/kaleido_mac.tar.gz"
[[kaleido]]
arch = "x86_64"
git-tree-sha1 = "eaf6781d8951eda81e75724d9c53b719e680ff30"
libc = "glibc"
os = "linux"

    [[kaleido.download]]
    sha256 = "b034f442d9b073ef19e23ef0f035b5143a84b9de5d41b2ae9ab9f008fd531301"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/v0.5.0/kaleido_linux_x64.tar.gz"
[[kaleido]]
arch = "x86_64"
git-tree-sha1 = "e59b69146f22d02079c8bf816e098c3de3b04fdd"
os = "windows"

    [[kaleido.download]]
    sha256 = "34d529cdb5222df629a34da73f08e37d77061eb963e6a4726ba2897ebcd3f0ae"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/v0.5.0/kaleido_win_x64.tar.gz"
[[kaleido]]
arch = "i686"
git-tree-sha1 = "76352e01edb575bb8d9b29b6cc0ca4a2049c237e"
os = "windows"

    [[kaleido.download]]
    sha256 = "da591d9ab033230c3a3ac7d366251c18ce90d165444f422ddc4e3fb38e447177"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/v0.5.0/kaleido_win_x86.tar.gz"
